export const REQUEST_LOAD_DICTIONARIES = 'REQUEST_LOAD_DICTIONARIES';
export const LOAD_DICTIONARIES = 'LOAD_DICTIONARIES';
export const DICTIONARIES_LOADED = 'DICTIONARIES_LOADED';

export const REQUEST_CREATE_DICTIONARY = 'REQUEST_CREATE_DICTIONARY';
export const CREATE_DICTIONARY = 'CREATE_DICTIONARY';
export const DICTIONARY_CREATED = 'DICTIONARY_CREATED';

export const REQUEST_EDIT_DICTIONARY = 'REQUEST_EDIT_DICTIONARY';
export const EDIT_DICTIONARY = 'EDIT_DICTIONARY';
export const DICTIONARY_EDITED = 'DICTIONARY_EDITED';

export const REQUEST_CHANGE_ACTIVENESS_OF_DICTIONARY = 'REQUEST_CHANGE_ACTIVENESS_OF_DICTIONARY';
export const CHANGE_ACTIVENESS_OF_DICTIONARY = 'CHANGE_ACTIVENESS_OF_DICTIONARY';
export const DICTIONARY_ACTIVENESS_CHANGED = 'DICTIONARY_ACTIVENESS_CHANGED';

export const REQUEST_DELETE_DICTIONARY = 'REQUEST_DELETE_DICTIONARY';
export const DELETE_DICTIONARY = 'DELETE_DICTIONARY';
export const DICTIONARY_DELETED = 'DICTIONARY_DELETED';

export const REQUEST_REGISTER = 'REQUEST_REGISTER';
export const REQUEST_REGISTER_LOCALDB = 'REQUEST_REGISTER_LOCALDB';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_SUCCESS_LOCALDB = 'REGISTER_SUCCESS_LOCALDB';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';

// This is also used in backend ipc.
// Note that there is no callback for this backend ipc action.
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// This is also used in backend ipc.
// Note that there is no callback for this backend ipc action.
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const LOAD_USER = 'LOAD_USER';

export const REQUEST_LOAD_ONLINE_SOURCES = 'REQUEST_LOAD_ONLINE_SOURCES';
export const LOAD_ONLINE_SOURCES = 'LOAD_ONLINE_SOURCES';
export const ONLINE_SOURCES_LOADED = 'ONLINE_SOURCES_LOADED';

export const REQUEST_CREATE_ONLINE_SOURCE = 'REQUEST_CREATE_ONLINE_SOURCE';
export const CREATE_ONLINE_SOURCE = 'CREATE_ONLINE_SOURCE';
export const ONLINE_SOURCE_CREATED = 'ONLINE_SOURCE_CREATED';

export const REQUEST_EDIT_ONLINE_SOURCE = 'REQUEST_EDIT_ONLINE_SOURCE';
export const EDIT_ONLINE_SOURCE = 'EDIT_ONLINE_SOURCE';
export const ONLINE_SOURCE_EDITED = 'ONLINE_SOURCE_EDITED';

export const REQUEST_DELETE_ONLINE_SOURCE = 'REQUEST_DELETE_ONLINE_SOURCE';
export const DELETE_ONLINE_SOURCE = 'DELETE_ONLINE_SOURCE';
export const ONLINE_SOURCE_DELETED = 'ONLINE_SOURCE_DELETED';
