export const EDIT_DICTIONARY = 'EDIT_DICTIONARY';
export const DELETE_DICTIONARY = 'DELETE_DICTIONARY';
export const CHANGE_ACTIVENESS_OF_DICTIONARY = 'CHANGE_ACTIVENESS_OF_DICTIONARY';

export const REQUEST_CREATE_DICTIONARY = 'REQUEST_CREATE_DICTIONARY';
export const CREATE_DICTIONARY = 'CREATE_DICTIONARY';
export const DICTIONARY_CREATED = 'DICTIONARY_CREATED';