export const REQUEST_LOAD_DICTIONARIES = 'REQUEST_LOAD_DICTIONARIES';
export const LOAD_DICTIONARIES = 'LOAD_DICTIONARIES';
export const DICTIONARIES_LOADED = 'DICTIONARIES_LOADED';

export const REQUEST_CREATE_DICTIONARY = 'REQUEST_CREATE_DICTIONARY';
export const CREATE_DICTIONARY = 'CREATE_DICTIONARY';
export const DICTIONARY_CREATED = 'DICTIONARY_CREATED';

export const REQUEST_EDIT_DICTIONARY = 'REQUEST_EDIT_DICTIONARY';
export const EDIT_DICTIONARY = 'EDIT_DICTIONARY';
export const DICTIONARY_EDITED = 'DICTIONARY_EDITED';

export const REQUEST_CHANGE_ACTIVENESS_OF_DICTIONARY = 'REQUEST_CHANGE_ACTIVENESS_OF_DICTIONARY';
export const CHANGE_ACTIVENESS_OF_DICTIONARY = 'CHANGE_ACTIVENESS_OF_DICTIONARY';
export const DICTIONARY_ACTIVENESS_CHANGED = 'DICTIONARY_ACTIVENESS_CHANGED';

export const REQUEST_DELETE_DICTIONARY = 'REQUEST_DELETE_DICTIONARY';
export const DELETE_DICTIONARY = 'DELETE_DICTIONARY';
export const DICTIONARY_DELETED = 'DICTIONARY_DELETED';

export const REQUEST_REGISTER = 'REQUEST_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';