export const CHANGE_CURRENT_WORD = 'CHANGE_CURRENT_WORD';

export const REQUEST_SAVE_DEFINITION = 'REQUEST_SAVE_DEFINITION';
export const SAVE_DEFINITION = 'SAVE_DEFINITION';
export const DEFINITION_SAVED = 'DEFINITION_SAVED';

export const REQUEST_FIND_DEFINITIONS_OF_WORD = 'REQUEST_FIND_DEFINITIONS_OF_WORD';
export const FIND_DEFINITIONS_OF_WORD = 'FIND_DEFINITIONS_OF_WORD';
export const FOUND_DEFINITIONS_OF_WORD = 'FOUND_DEFINITIONS_OF_WORD';