export const CHANGE_CURRENT_WORD = 'CHANGE_CURRENT_WORD';

export const REQUEST_SAVE_DEFINITION = 'REQUEST_SAVE_DEFINITION';
export const SAVE_DEFINITION = 'SAVE_DEFINITION';
export const DEFINITION_SAVED = 'DEFINITION_SAVED';