export const CHANGE_CURRENT_WORD = 'CHANGE_CURRENT_WORD';

export const REQUEST_SAVE_DEFINITION = 'REQUEST_SAVE_DEFINITION';
export const SAVE_DEFINITION = 'SAVE_DEFINITION';
export const DEFINITION_SAVED = 'DEFINITION_SAVED';

export const REQUEST_FIND_DEFINITIONS_OF_WORD = 'REQUEST_FIND_DEFINITIONS_OF_WORD';
export const FIND_DEFINITIONS_OF_WORD = 'FIND_DEFINITIONS_OF_WORD';
export const FOUND_DEFINITIONS_OF_WORD = 'FOUND_DEFINITIONS_OF_WORD';

export const REQUEST_DELETE_DEFINITION = 'REQUEST_DELETE_DEFINITION';
export const DELETE_DEFINITION = 'DELETE_DEFINITION';
export const DEFINITION_DELETED = 'DEFINITION_DELETED';

export const REQUEST_EDIT_DEFINITION = 'REQUEST_EDIT_DEFINITION';
export const EDIT_DEFINITION = 'EDIT_DEFINITION';
export const DEFINITION_EDITED = 'DEFINITION_EDITED';

export const MERGE_DEFINITIONS_RESULT = 'MERGE_DEFINITIONS_RESULT';

export const HIDE_DEFINITION_SAVE_MESSAGE = 'HIDE_DEFINITION_SAVE_MESSAGE';
