export const REQUEST_LOAD_ONLINE_SOURCES = 'REQUEST_LOAD_ONLINE_SOURCES';
export const LOAD_ONLINE_SOURCES = 'LOAD_ONLINE_SOURCES';
export const ONLINE_SOURCES_LOADED = 'ONLINE_SOURCES_LOADED';

export const REQUEST_UPSERT_ONLINE_SOURCE = 'REQUEST_UPSERT_ONLINE_SOURCE';
export const UPSERT_ONLINE_SOURCE = 'UPSERT_ONLINE_SOURCE';
export const ONLINE_SOURCE_CREATED = 'ONLINE_SOURCE_CREATED';
export const ONLINE_SOURCE_EDITED = 'ONLINE_SOURCE_EDITED';

// using upsert instead...
// export const REQUEST_EDIT_ONLINE_SOURCE = 'REQUEST_EDIT_ONLINE_SOURCE';
// export const EDIT_ONLINE_SOURCE = 'EDIT_ONLINE_SOURCE';

export const REQUEST_DELETE_ONLINE_SOURCE = 'REQUEST_DELETE_ONLINE_SOURCE';
export const DELETE_ONLINE_SOURCE = 'DELETE_ONLINE_SOURCE';
export const ONLINE_SOURCE_DELETED = 'ONLINE_SOURCE_DELETED';

export const REQUEST_LOAD_ONLINE_SOURCES_OF_ACTIVE_DICTIONARIES = 'REQUEST_LOAD_ONLINE_SOURCES_OF_ACTIVE_DICTIONARIES';
export const LOAD_ONLINE_SOURCES_OF_ACTIVE_DICTIONARIES = 'LOAD_ONLINE_SOURCES_OF_ACTIVE_DICTIONARIES';
export const ONLINE_SOURCES_OF_DICTIONARIES_LOADED = 'ONLINE_SOURCES_OF_DICTIONARIES_LOADED'; 