export const REQUEST_LOAD_ALL_SETTINGS = 'REQUEST_LOAD_ALL_SETTINGS';
export const LOAD_ALL_SETTINGS = 'LOAD_ALL_SETTINGS';
export const ALL_SETTINGS_LOADED = 'ALL_SETTINGS_LOADED';

export const REQUEST_CHANGE_VERBOSITY = 'REQUEST_CHANGE_VERBOSITY';
export const CHANGE_VERBOSITY = 'CHANGE_VERBOSITY';
export const VERBOSITY_CHANGED = 'VERBOSITY_CHANGED';
