export const REQUEST_START_STUDY = 'REQUEST_START_STUDY';
export const START_STUDY = 'START_STUDY';
export const STUDY_READY = 'STUDY_READY';

export const REQUEST_FINISIH_STUDY = 'REQUEST_FINISIH_STUDY';
export const FINISH_STUDY = 'FINISH_STUDY';
export const STUDY_FINISHED = 'STUDY_FINISHED';
export const STUDY_REJECTED = 'STUDY_REJECTED';
